config/routes.rb
Rails.application.routes.draw do
  resources :audit_logs do
    member do
      get :confirm
    end
  end
  namespace :admin do
      resources :posts
      resources :users
      resources :admin_users
      resources :employees
      

      root to: "posts#index"
    end
  resources :posts do
    member do
      get :approve
    end
  end
  devise_for :users, skip: [:registrations]
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root "statics#home"
  resources :employees
end

app/views/shared/_audit_log_tab.html.erb
<li class="nav-item nav-link <%= active?(audit_logs_path)%>">
    <%= link_to "Audit Log", audit_logs_path, style:"text-decoration: none;" %>
</li>

app/views/shared/_employee_nav.html.erb
<li class="nav-item nav-link <%= active?(posts_path)%>">
            <%= link_to "Time Entries", posts_path, style:"text-decoration: none;" %>
</li>

<li class="nav-item nav-link <%= active?(new_post_path)%>">
    <%= link_to "Request Overtime", new_post_path, style:"text-decoration: none;", id:"new_post_link" %>
</li>

app/views/shared/_nav.html.erb
<h1>Time Tracker.</h1>
<% if current_user %>
    <ul class="nav nav-tabs" style="margin-top: 15px;">
        <li class="nav-item nav-link <%= active?(root_path)%>">
            <%= link_to "Home", root_path, style:"text-decoration: none;" %>
        </li>

        <%= render "shared/employee_nav" if employee? %>

        <%= render "shared/audit_log_tab" if admin? %>
        

    
        <li class="nav-item dropdown ml-md-auto nav">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-bs-toggle="dropdown">Options</a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuLink">
           <% if admin? %>
                    <%= link_to "GOTO: Admin Dashboard", admin_root_path, class:"dropdown-item" %>
                <div class="dropdown-divider"></div> 
            <% end %>
                <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:"dropdown-item" %>
            </div>
        </li>
        
    </ul>
<% end %>




    