config/routes.rb
Rails.application.routes.draw do
  resources :audit_logs do
    member do
      get :confirm
    end
  end
  namespace :admin do
      resources :posts
      resources :users
      resources :admin_users
      resources :employees
      

      root to: "posts#index"
    end
  resources :posts do
    member do
      get :approve
    end
  end
  devise_for :users, skip: [:registrations]
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root "statics#home"
  resources :employees
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController

    def home
        if admins_who_can_access.include?(current_user.type)
            @pending_approvals = Post.submitted
            @recent_audit_logs = AuditLog.last(10)
        else
            @pending_audit_confirmations = current_user.audit_logs.pending.sort_by_start_date
        end
    end
end

app/views/statics/_admin.html.erb
<style>
    .pending-homepage{
        margin-top: 20px;
        margin-bottom: 20px;
        background-color: #E3E3E3;
        -webkit-border-radius: 3px;
        -moz-border-radius: 3px;
        border-radius: 3px;
        padding:20px;
    }

    .homepage-block{
        background-color: #1D3C91;
        color: white;
        margin: 12px 42px 12px 42px;
        padding: 15px;
        -webkit-border-radius: 3px;
        -moz-border-radius: 3px;
        border-radius: 3px;
    }

    .pending-details{
        font-weight: 900;
    }
    .rev-btn-col{
        color: white;
    }
    .rev-btn-col:hover{
        color: white;
        background: #e0a800;
    }
    
    .homepage-block:hover{
        background: #0a256e;
    }

</style>

<div class="container-fluid">
    <div class="pending-homepage row">
        <h1>Items Pending Your Approvals</h1>
        <hr>

        <%= render partial: "pending_approval", locals: {pending_approvals: @pending_approvals} %>
        
    </div>
    <hr>

    <div class="pending-homepage row">
        <h1>Confirmation Log</h1>
        <hr>

        <%= render partial: "confirmation_log", locals: {recent_audit_logs: @recent_audit_logs} %>
    
    
    </div>
</div>

app/views/statics/_confirmation_log.html.erb
<% recent_audit_logs.each do |recent_audit_log| %>

    <div class="homepage-block col-md-3">
        <h4>
            <%= recent_audit_log.user.full_name %>
        </h4>

        <p>
            <span class="pending-details">Date Submitted: </span> <%= recent_audit_log.start_date %>
        </p>
        <p>
            <span class="pending-details">Confirmed At: </span> <%= recent_audit_log.end_date || status_labels('pending') %>
        </p>
        <p>
            <span class="pending-details">Status: </span> <%= status_labels recent_audit_log.status %>
        </p>

        
    </div>


<% end %>

app/views/statics/_employee.html.erb
<style>
    .jumbotron {
    padding: 2rem 2rem;
    background-color: #e9ecef;
    border-radius: .3rem;
    margin: 10px;
    }

    .centre{
    display: flex;
    justify-content: center;
    align-items: center;
    }
    .margin-employee-btn{
        margin:15px;
    }
</style>

<div class="container-fluid">
    <div class="row centre">
        <% if @pending_audit_confirmations.count > 0 %>
            <div class="jumbotron">
                <%= render partial: "pending_audit_confirmations", locals: {pending_audit_confirmations: @pending_audit_confirmations}%>
            </div>
        <% end %>

        <div class="jumbotron">
            <%= link_to "Request Overtime !", new_post_path, class:"btn btn-primary form-control btn-lg"%>
        </div>
    </div>
</div>

app/views/statics/_pending_approval.html.erb
<% pending_approvals.each do |pending_approval| %>

    <div class="homepage-block col-md-3">
        <h4>
            <%= pending_approval.user.full_name %>
        </h4>

        <p>
            <span class="pending-details">Date Submitted: </span> <%= pending_approval.date %>
        </p>
        <p>
            <span class="pending-details">Rationale: </span> <%= truncate(pending_approval.rationale, length: 42)%>
        </p>

        <div class="row">
            <div class="col-md-6">
                <%= link_to "Approve", approve_post_path(pending_approval), class:"btn btn-success form-control", id: "approve#{pending_approval.id}"%>
            </div>

            <div class="col-md-6">
                <%= link_to "Review", edit_post_path(pending_approval), class:"btn btn-warning form-control rev-btn-col"%>
            </div>
        </div>
    </div>


<% end %>

app/views/statics/_pending_audit_confirmations.html.erb
<h3 class="text-center">Confirm Your Pending Audits</h3><hr>
<% pending_audit_confirmations.each do |pending_audit_confirmation| %>
    <div class="margin-employee-btn">
        <%= link_to "I confirm that i did not perform any overtime for the week of #{pending_audit_confirmation.start_date} through #{pending_audit_confirmation.start_date + 6.days}", confirm_audit_log_path(pending_audit_confirmation), class:"btn btn-primary form-control btn-lg", id:"confirm_#{pending_audit_confirmation.id}"%>
    </div>
<% end %>
<hr>

app/views/statics/home.html.erb
<% if admins_who_can_access.include?(current_user.try(:type)) %> 
    <%= render "statics/admin" %>
<% else %>
    <%= render "statics/employee" %>
<% end %>